### ISSUE TITLE
Issue in CI

### ISSUE THREAD

**Issue by kif** [kif/freesas#68]
Probably related to new features in numpy:

```
======================================================================
ERROR: test_load_data_with_unescaped_footer (freesas.test.test_sasio.TestSasIO)
Test that an unescaped footer does not hinder loading.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/freesas/build/lib.linux-x86_64-3.9/freesas/test/test_sasio.py", line 139, in test_load_data_with_unescaped_footer
    data = load_scattering_data("test")
  File "/tmp/freesas/build/lib.linux-x86_64-3.9/freesas/sasio.py", line 39, in load_scattering_data
    data = loadtxt(filename)
  File "/tmp/pipmamba39/lib/python3.9/site-packages/numpy/lib/npyio.py", line 1313, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "/tmp/pipmamba39/lib/python3.9/site-packages/numpy/lib/npyio.py", line 979, in _read
    arr = _load_from_filelike(
TypeError: encoding must be a unicode string.

```

**Comment by kif** [comment]
The issue comes from the  monkey-patching performed in the test:
```
        mocked_open = mock_open(read_data=file_data)
        with patch('builtins.open', mocked_open):
            with patch('numpy.DataSource.open', mocked_open):
```

**Comment by kif** [comment]
monkey patching is bad ... and `numpy.loadtxt` changed behaviour. Needs fix
